app/frontend/__init__.py
#!/usr/bin/env python3
from flask import Blueprint

frontend = Blueprint(
    'frontend',
    __name__,
    url_prefix='/me',
    static_folder='static',
    template_folder='templates'
)

from app.frontend.views import *

app/frontend/views.py
from models import db
from typing import Dict
from urllib.parse import quote
from app.frontend import frontend
from flask.typing import ResponseReturnValue
from flask import (
    url_for,
    render_template
)


@frontend.app_template_filter('urlencode')
def urlencode_filter(value: str) -> str:
    return quote(value)


@frontend.context_processor
def inject_now() -> Dict:
    from datetime import datetime
    return {'now': datetime.now}


@frontend.errorhandler(404)
def handle_404(_: Exception) -> ResponseReturnValue:
    return render_template(url_for('frontend.error'))


@frontend.context_processor
def inject_user_profile():
    from os import getenv
    from models.user import User

    email = getenv('USER_EMAIL') or 'daniell.olaitan@gmail.com'
    user = db.fetch_object(User, email=email)

    profile = user.profile.to_json()
    current_user = user.to_json()
    current_user['profile'] = profile

    services = [service.to_json() for service in user.profile.services]
    contacts = [contact.to_json() for contact in user.profile.contacts]
    current_user['profile']['services'] = services
    current_user['profile']['contacts'] = contacts

    return dict(current_user=current_user)


@frontend.route('/contact-me', methods=['GET', 'POST'])
def contact_me() -> ResponseReturnValue:
    pass


@frontend.route('/error', methods=['GET'])
def error() -> ResponseReturnValue:
    return render_template('error.html')


@frontend.route('/', methods=['GET'])
def home() -> ResponseReturnValue:
    headers = [
        {'name': 'me', 'url': url_for('frontend.home'), 'selected': True},
        {'name': 'projects', 'url': url_for('frontend.get_projects')},
        {'name': 'work', 'url': url_for('frontend.get_works')},
        {'name': 'articles', 'url': url_for('frontend.get_articles')},
        {'name': 'open source contribution', 'url': url_for('frontend.get_contributions')}
    ]

    return render_template('home.html', headers=headers)


@frontend.route('/projects', methods=['GET'])
def get_projects() -> ResponseReturnValue:
    from os import getenv
    from models.user import User

    email = getenv('USER_EMAIL') or 'daniell.olaitan@gmail.com'
    user = db.fetch_object(User, email=email)
    headers = [
        {'name': 'me', 'url': url_for('frontend.home')},
        {'name': 'projects', 'url': url_for('frontend.get_projects'), 'selected': True},
        {'name': 'work', 'url': url_for('frontend.get_works')},
        {'name': 'articles', 'url': url_for('frontend.get_articles')},
        {'name': 'open source contribution', 'url': url_for('frontend.get_contributions')}
    ]

    projects = []
    for project in user.projects:
        features = [feature.to_json() for feature in project.features]
        print(project.title)
        project = project.to_json()
        project['features'] = features
        projects.append(project)

    return render_template('projects.html', headers=headers, projects=projects)


@frontend.route('/works', methods=['GET'])
def get_works() -> ResponseReturnValue:
    from os import getenv
    from models.user import User

    email = getenv('USER_EMAIL') or 'daniell.olaitan@gmail.com'
    user = db.fetch_object(User, email=email)
    headers = [
        {'name': 'me', 'url': url_for('frontend.home')},
        {'name': 'projects', 'url': url_for('frontend.get_projects')},
        {'name': 'work', 'url': url_for('frontend.get_works'), 'selected': True},
        {'name': 'articles', 'url': url_for('frontend.get_articles')},
        {'name': 'open source contribution', 'url': url_for('frontend.get_contributions')}
    ]

    works = []
    for work in user.works:
        experiences = [experience.to_json() for experience in work.experiences]
        work = work.to_json()
        work['experiences'] = experiences
        works.append(work)

    return render_template('works.html', headers=headers, works=works)


@frontend.route('/articles', methods=['GET'])
def get_articles() -> ResponseReturnValue:
    from os import getenv
    from models.user import User

    email = getenv('USER_EMAIL') or 'daniell.olaitan@gmail.com'
    user = db.fetch_object(User, email=email)
    headers = [
        {'name': 'me', 'url': url_for('frontend.home')},
        {'name': 'projects', 'url': url_for('frontend.get_projects')},
        {'name': 'work', 'url': url_for('frontend.get_works')},
        {'name': 'articles', 'url': url_for('frontend.get_articles'), 'selected': True},
        {'name': 'open source contribution', 'url': url_for('frontend.get_contributions')}
    ]

    articles = [article.to_json() for article in user.articles]
    return render_template('articles.html', headers=headers, articles=articles)


@frontend.route('/articles/<string:article_id>', methods=['GET'])
def get_article(article_id: str) -> ResponseReturnValue:
    from models.article import Article

    article = db.fetch_object(Article, id=article_id)
    if not article:
        return render_template(url_for('frontend.error'))

    article = article.to_json()
    headers = [
        {'name': 'me', 'url': url_for('frontend.home')},
        {'name': 'projects', 'url': url_for('frontend.get_projects')},
        {'name': 'work', 'url': url_for('frontend.get_works')},
        {'name': 'articles', 'url': url_for('frontend.get_articles'), 'selected': True},
        {'name': 'open source contribution', 'url': url_for('frontend.get_contributions')}
    ]

    return render_template('article.html', headers=headers, article=article)


@frontend.route('/contributions', methods=['GET'])
def get_contributions() -> ResponseReturnValue:
    from os import getenv
    from models.user import User

    email = getenv('USER_EMAIL') or 'daniell.olaitan@gmail.com'
    user = db.fetch_object(User, email=email)
    headers = [
        {'name': 'me', 'url': url_for('frontend.home')},
        {'name': 'projects', 'url': url_for('frontend.get_projects')},
        {'name': 'work', 'url': url_for('frontend.get_works')},
        {'name': 'articles', 'url': url_for('frontend.get_articles')},
        {
            'name': 'open source contribution',
            'url': url_for('frontend.get_contributions'),
            'selected': True
        }
    ]

    contributions = []
    for contribution in user.contributions:
        gitrefs = [gitref.to_json() for gitref in contribution.git_refs]
        contribution = contribution.to_json()
        contribution['gitrefs'] = gitrefs
        contributions.append(contribution)

    return render_template('contributions.html', headers=headers, contributions=contributions)

app/frontend/templates/article.html
{% extends "parent.html" %}
{% block title %}Article | Portfolio{% endblock %}
{% block content %}
<div class="mx-auto max-w-5xl">
  <div class="flex flex-col gap-6 text-justify mb-14 xl:mb-20 border-b-2 pb-12 border-gray-300">
    <h1 class="capitalize">{{ article.title }}</h1>
    <ul class="flex gap-2">
      {% for tag in article.tags %}
      <li>
        <span
          class="text-lg text-blue-500 border-blue-500 border cursor-pointer rounded-full py-1 px-2 opacity-100 hover:opacity-50 transition-opacity duration-200"
        >
          {{ tag }}
        </span>
      </li>
      {% endfor %}
    </ul>
  </div>

  <p class="text-xl sm:text-2xl text-justify">{{ article.content }}</p>

</div>
{% endblock %}

app/frontend/templates/articles.html
{% extends "parent.html" %}
{% block title %}Articles | Portfolio{% endblock %}
{% block content %}
<div class="mx-auto max-w-5xl">
  <div class="flex flex-col gap-6 text-justify mb-14 xl:mb-20 border-b-2 pb-12 border-gray-300">
    <h1 class="capitalize">Articles</h1>
    {% if current_user.profile.article_header %}
      <p class="text-xl sm:text-2xl">{{ current_user.profile.article_header }}</p>
    {% endif %}
  </div>

  <ul>
    {% if articles %}
      {% for article in articles %}
        <li class="flex flex-col gap-8 mb-10 sm:mb-14 xl:mb-20 border-b-2 last:border-b-0 pb-12 border-gray-300">
          <div class="flex flex-col gap-3">
            <h2>{{ article.title }}</h2>
            <ul class="flex gap-2">
              {% for tag in article.tags %}
              <li>
                <span
                  class="text-lg text-blue-500 border-blue-500 border rounded-full py-1 px-2 opacity-100 hover:opacity-50 transition-opacity duration-200"
                >
                  {{ tag }}
                </span>
              </li>
              {% endfor %}
            </ul>
            <p class="text-lg sm:text-xl text-gray-500">{{ article.created_at.split('T')[0] }}</p>
          </div>

          <p class="text-xl sm:text-2xl text-justify">{{ article.content | truncate(300) }}</p>

          <a
            href="{{ url_for('frontend.get_article', article_id=article.id) }}"
            class="w-max-content hover:opacity-50 text-blue-500 font-semibold after:content-['>'] text-xl"
          >
            Read Article
          </a>

        </li>
      {% endfor %}
    {% else %}
      <div class="text-xl sm:text-2xl text-justify">No articles available.</div>
    {% endif %}
  </ul>
</div>
{% endblock %}

app/frontend/templates/contributions.html
{% extends "parent.html" %}
{% block title %}Contributions | Portfolio{% endblock %}
{% block content %}
<div class="mx-auto max-w-5xl">
  <div class="flex flex-col gap-6 text-justify mb-14 xl:mb-20 border-b-2 pb-12 border-gray-300">
    <h1 class="capitalize">Contributions</h1>
    {% if current_user.profile.contribution_header %}
      <p class="text-xl sm:text-2xl">{{ current_user.profile.contribution_header }}</p>
    {% endif %}
  </div>

  <ul>
    {% if contributions %}
      {% for contribution in contributions %}
        <li class="flex flex-col gap-8 mb-10 sm:mb-14 xl:mb-20 border-b-2 last:border-b-0 pb-12 border-gray-300">

          <div class="flex flex-col gap-3">
            <h2>{{ contribution.name }}</h2>
            <p class="text-lg sm:text-xl text-gray-500">Date: {{ contribution.date }}</p>
            <p class="text-lg sm:text-xl text-gray-500">Type: {{ contribution.contribution_type }}</p>
            <p class="text-lg sm:text-xl text-gray-500">Role: {{ contribution.role }}</p>
          </div>

          <div class="flex flex-col gap-2 mb-8">
            <h3 class="text-gray-600">Descriptions:</h3>
            <ul class="flex flex-col gap-4 text-xl sm:text-2xl">
            {% for description in contribution.descriptions %}
              <li class="text-xl sm:text-2xl text-gray-500">
                <p class="before:content-['>'] text-xl sm:text-2xl text-justify">{{ description }}</p>
              </li>
            {% endfor %}
            </ul>
          </div>

          {% if contribution.gitrefs %}
            <div class="flex flex-col gap-2 mb-8">
              <h3 class="text-gray-600">Contributions:</h3>
              <ul class="flex flex-col gap-16 text-xl sm:text-2xl">
              {% for gitref in contribution.gitrefs %}
                <li class="text-xl sm:text-2xl text-gray-500 flex flex-col gap-8">
                  <div class="flex flex-col gap-3">
                    <p class="text-xl sm:text-2xl">commit id: <span class="text-blue-500">{{ gitref.commit_id }}</span></p>
                    <p class="text-xl sm:text-2xl">status: {{ gitref.status }}</p>
                  </div>

                  <div class="flex gap-12">
                    <a
                      href="{{ gitref.pull_request_url }}"
                      class="w-max-content hover:opacity-50 text-blue-500 font-semibold text-xl"
                    >
                      View Pull Request
                    </a>

                    {% if gitref.issue_url %}
                      <a
                        href="{{ gitref.issue_url }}"
                        class="w-max-content hover:opacity-50 text-blue-500 font-semibold text-xl"
                      >
                        View Issue
                      </a>
                    {% endif %}
                </li>
              {% endfor %}
              </ul>
            </div>
          {% endif %}

          <div class="flex flex-col gap-2 mb-8">
            <h3 class="text-gray-600">Technologies used:</h3>
            <ul class="flex flex-col gap-4 text-xl sm:text-2xl">
            {% for technology in contribution.technologies %}
              <li class="text-xl sm:text-2xl text-gray-500">
                <p class="before:content-['>'] text-xl sm:text-2xl text-justify">{{ technology }}</p>
              </li>
            {% endfor %}
            </ul>
          </div>

          <div class="flex flex-col gap-2 mb-8">
            <h3 class="text-gray-600">The skills gained/honed from this contribution are:</h3>
            <ul class="flex flex-col gap-4 text-xl sm:text-2xl">
            {% for skill in contribution.skills %}
              <li class="text-xl sm:text-2xl text-gray-500">
                <p class="before:content-['>'] text-xl sm:text-2xl text-justify">{{ skill }}</p>
              </li>
            {% endfor %}
            </ul>
          </div>

          <div class="flex flex-col gap-2 mb-8">
            <h3 class="text-gray-600">Impacts of the contribution are:</h3>
            <ul class="flex flex-col gap-4 text-xl sm:text-2xl">
            {% for impact in contribution.impacts %}
              <li class="text-xl sm:text-2xl text-gray-500">
                <p class="before:content-['>'] text-xl sm:text-2xl text-justify">{{ impact }}</p>
              </li>
            {% endfor %}
            </ul>
          </div>
          {% if contribution.repo_url %}
            <a
              href="{{ contribution.repo_url }}"
              class="w-max-content hover:opacity-50 bg-blue-500 text-white font-semibold py-3 px-5 rounded"
              target="_blank"
            >
              Github Repo
            </a>
          {% endif %}
        </li>
      {% endfor %}
    {% else %}
      <div class="text-xl sm:text-2xl text-justify">No contributions available.</div>
    {% endif %}
  </ul>
</div>
{% endblock %}

app/frontend/templates/error.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('frontend.static', filename='css/output.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
    <title>{% block title %}Daniel Olaitan | Backend Engineer{% endblock %}</title>
  </head>
  <body class="p-0">
    <div class="flex flex-col items-center justify-center min-h-screen text-xl sm:text-2xl bg-gray-100">
      <h1 class="text-9xl font-extrabold text-gray-800">404</h1>
      <p class="text-gray-500 mt-2">Sorry, the page you are looking for does not exist.</p>
      <a
          href="{{ url_for('frontend.home') }}"
          class="mt-8 px-6 py-2 bg-blue-600 text-white text-lg font-medium rounded-lg hover:bg-blue-700 transition duration-200"
      >
        Go Back Home
      </a>
    </div>
  </body>
</html>

app/frontend/templates/home.html
{% extends "parent.html" %}
{% block title %}{{ current_user.name }} | Portfolio{% endblock %}
{% block content %}
<div class="mx-auto max-w-5xl">
  <section class="flex flex-col gap-6 text-justify mb-10 sm:mb-14 xl:mb-20 border-b-2 pb-12 border-gray-300">
    <div class="flex flex-col gap-3 items-center">
      {% if current_user.profile.tagline %}
      <h3 class="text-center">{{ current_user.profile.tagline }}</h3>
      {% endif %}
      {% if current_user.profile.location %}
      <p class="text-lg sm:text-xl text-gray-500">{{ current_user.profile.location }}</p>
      {% endif %}
      <div class="flex gap-3 mb-12">
        <p class="text-lg sm:text-xl text-gray-500">
          Phone: <span class="text-blue-500">{{ current_user.phone }}</span>
        </p> |
        <p class="text-lg sm:text-xl text-gray-500">
          Email: <a href="mailto:{{ current_user.email }}" class="text-blue-500 hover:underline">{{ current_user.email }}</a>
        </p>
      </div>
      <a
        href="#contact"
        class="w-max-content hover:opacity-50 bg-blue-500 text-white font-semibold py-3 px-5 rounded"
      >
        Contact Me
      </a>
    </div>
  </section>

  <section class="flex flex-col gap-12 items-center mb-10 sm:mb-14 xl:mb-20 border-b-2 last:border-b-0 pb-12 border-gray-300">
    <h2>About Me</h2>
    {% if current_user.profile.bio %}
    <p class="text-xl sm:text-2xl text-justify">{{ current_user.profile.bio }}</p>
    {% endif %}
  </section>

  <section class="flex flex-col gap-6 text-justify mb-10 sm:mb-14 xl:mb-20 border-b-2 pb-12 border-gray-300">
    <div class="flex flex-col gap-12 items-center">
      <h2>Services/Expertise</h2>
      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
        {% for service in current_user.profile.services %}
        <div class="p-6 bg-white rounded-lg shadow-lg text-center">
            <h3 class="mb-4">{{ service.title }}</h3>
            <p class="text-lg sm:text-xl">{{ service.description }}</p>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <section class="flex flex-col gap-8 items-center mb-10 sm:mb-14 xl:mb-20 border-b-2 last:border-b-0 pb-12 border-gray-300">
    <div class="flex flex-col gap-12 items-center mb-12">
      <h2>Ready to collaborate?</h2>
      <p class="text-xl sm:text-2xl text-justify">
        Contact me today to discuss how I can help bring your project to life or how I can join your team!
      </p>
    </div>
    <a
        href="#contact"
        class="w-max-content hover:opacity-50 bg-blue-500 text-white font-semibold py-3 px-5 rounded"
      >
        Get In Touch
      </a>
  </section>

  <section id="contact" class="flex flex-col gap-8 items-center mb-10 sm:mb-14 xl:mb-20 border-b-2 last:border-b-0 pb-12 border-gray-300">
    <h2>Connect With Me</h2>
    <div class="flex flex-col gap-3 items-center mb-36">
      <div class="flex flex-col gap-4 items-center">
      {% for contact in current_user.profile.contacts %}
        <div class="flex flex-col gap-3 items-center sm:flex-row sm:gap-2">
          <h3>{{ contact.name | capitalize }}:</h3>
          <a
            href="{{ contact.url }}"
            class="w-max-content hover:opacity-50 text-blue-500 font-semibold cursor-pointer text-xl"
            target="_blank"
          >
            {{ contact.url }}
          </a>
        </div>
      {% endfor %}
      </div>
      <div class="flex flex-col gap-2 items-center  sm:flex-row sm:gap-2">
        <h3>Email:</h3>
        <a
          href="mailto:{{ current_user.email }}"
          class="w-max-content hover:opacity-50 text-blue-500 font-semibold cursor-pointer text-xl"
          target="_blank"
        >
          {{ current_user.email }}
        </a>
      </div>
    </div>

    {% if current_user.profile.resume %}
    <div class="flex gap-12 flex-col items-center">
      <h1>My CV</h1>
      <div class="flex gap-8">
        <a
          href="{{ url_for('serve_file', filename=current_user.profile.resume) }}"
          class="w-max-content hover:opacity-50 bg-blue-500 text-white font-semibold py-3 px-5 rounded"
          target="_blank"
        >
          View CV
        </a>

        <a
          href="{{ url_for('download_file', filename=current_user.profile.resume) }}"
          class="w-max-content hover:opacity-50 bg-blue-500 text-white font-semibold py-3 px-5 rounded"
          target="_blank"
        >
          Download CV
        </a>
      </div>
    </div>
    {% endif %}
  </section>

</div>
{% endblock %}

app/frontend/templates/parent.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/x-icon" href="{{ url_for('frontend.static', filename='images/favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('frontend.static', filename='css/output.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
    <title>{% block title %}Daniel Olaitan | Backend Engineer{% endblock %}</title>
  </head>
  <body>
    <header class="flex items-center flex-col sm:flex-row gap-6 sm:gap-10 mx-auto max-w-5xl">
      <div class="shrink-0">
          <a href="{{ url_for('frontend.home') }}">
            {% if current_user.profile.image_url %}
              {% set src = url_for('serve_file', filename=current_user.profile.image_url) %}
            {% else %}
              {% set src = url_for('frontend.static', filename='images/daniel-olaitan.jpg') %}
            {% endif %}
            <img
              class='rounded-full'
              width="150"
              height="150"
              src="{{ src }}"
              alt="Daniel Olaitan Picture"
              style="width: 200px; height: 200px;"
            />
          </a>
      </div>

      <div class="flex flex-col gap-4 items-center sm:items-start">
        <a
          href="{{ url_for('frontend.home') }}"
          class="text-gray-700 pb-1 border-b-4 border-blue-700 text-2xl sm:text-3xl tracking-wider font-bold uppercase"
          style="width: max-content"
        >
          {{ current_user.name }}
        </a>

        <nav class='mt-4 flex-wrap sm:mt-6 flex gap-4 sm:gap-8 justify-center sm:justify-start'>
          {% for header in headers %}
            {% if header.selected %}
              <a
                href="{{ header.url }}"
                class="font-medium text-lg text-blue-500 cursor-pointer">{{ header.name | upper }}</a>
            {% else %}
              <a
                href="{{ header.url }}"
                class="font-medium text-lg cursor-pointer hover:text-blue-500">{{ header.name | upper }}
              </a>
            {% endif %}
          {% endfor %}
        </nav>
      </div>
    </header>

    <div class="flex flex-col p-5 min-h-screen">
      <div class="p-5 sm:p-10 md:p-16 lg:p-24 flex-grow">
        {% block content %}{% endblock %}
      </div>

      <footer class='pt-12 border-t-2 border-gray-300 flex flex-col sm:flex-row items-center gap-8'>
        <p class="font-light text-xl">&copy; {{ now().year }} Daniel OLAITAN.</p>
        <div class='flex gap-8 sm:ml-auto'>
          {% set icon_style = 'text-2xl text-gray-400 hover:text-gray-600' %}
          <a href="https://www.linkedin.com/in/daniell-olaitan" target='_blank'>
              <i class="fa-brands fa-linkedin {{ icon_style }}"></i>
          </a>
          <a href="https://github.com/daniell-olaitan" target='_blank'>
              <i class="fa-brands fa-square-github {{ icon_style }}"></<title>Responsive Navbar</title>i>
          </a>
          <a href="https://x.com/daniell_olaitan" target='_blank'>
              <i class="fa-brands fa-square-x-twitter {{ icon_style }}"></i>
          </a>
          {% set whatsapp_number = '2348084078357' %}
          {% set message = 'Hello, I would like to contact you.' %}
          <a  href="https://wa.me/{{ whatsapp_number }}?text={{ message | urlencode }}" target='_blank'>
              <i class="fa-brands fa-square-whatsapp {{ icon_style }}"></i>
          </a>
        </div>

      </footer>
    </div>
  </body>
</html>

app/frontend/templates/projects.html
{% extends "parent.html" %}
{% block title %}Projects | Portfolio{% endblock %}
{% block content %}
<div class="mx-auto max-w-5xl">
  <div class="flex flex-col gap-6 text-justify mb-14 xl:mb-20 border-b-2 pb-12 border-gray-300">
    <h1 class="capitalize">Projects</h1>
    {% if current_user.profile.project_header %}
      <p class="text-xl sm:text-2xl">{{ current_user.profile.project_header }}</p>
    {% endif %}
  </div>

  <ul>
    {% if projects %}
      {% for project in projects %}
        <li class="flex flex-col gap-8 mb-10 sm:mb-14 xl:mb-20 border-b-2 last:border-b-0 pb-12 border-gray-300">

          <h2>{{ project.title }}</h2>

          {% if project.image_url %}
              <img
                class="rounded-2xl mb-12 shadow-xl inline-block" width="752" height="830" alt="Screenshot"
                src="{{ url_for('serve_file', filename=project.image_url) }}"
              />
          {% endif %}

          {% if project.video_url %}
              <video class="rounded-2xl mb-12 shadow-xl inline-block" controls width="752" height="830">
                <source src="{{ url_for('serve_file', filename=project.video_url) }}" type="video/mp4" />
                Your browser does not support the video tag.
              </video>
          {% endif %}

          <p class="text-xl sm:text-2xl text-justify">{{ project.description }}</p>

          {% if project.features %}
            <div class="flex flex-col gap-2 mb-8">
              <h3 class="text-gray-600">The features of the project are:</h3>
              <ul class="flex flex-col gap-8 text-xl sm:text-2xl">
              {% for feature in project.features %}
                <li class="text-xl sm:text-2xl text-gray-500">
                  <h3 class="text-gray-600">{{ feature.name }}</h3>
                  <p class="text-xl sm:text-2xl text-justify">{{ feature.description }}</p>
                </li>
              {% endfor %}
              </ul>
            </div>
          {% endif %}

          {% if project.skills %}
            <div class="flex flex-col gap-2 mb-20">
              <h3 class="text-gray-600">The skills gained/honed during the course of this project are:</h3>
              <ul class="flex flex-col gap-1 text-xl sm:text-2xl">
              {% for skill in project.skills %}
                <li class="before:content-['>'] text-xl sm:text-2xl text-gray-500">
                  {{ skill }}
                </li>
              {% endfor %}
              </ul>
            </div>
          {% endif %}
          <div class="flex gap-12">
            {% if project.github_url %}
              <a
                href="{{ project.github_url }}"
                class="w-max-content hover:opacity-50 bg-blue-500 text-white font-semibold py-3 px-5 rounded"
                target="_blank"
              >
                Github Repo
              </a>
            {% endif %}
            {% if project.project_url %}
              <a
                href="{{ project.project_url }}"
                class="w-max-content hover:opacity-50 bg-blue-500 text-white font-semibold py-3 px-5 rounded"
                target="_blank"
              >
                Visit Site
              </a>
            {% endif %}
          </div>
        </li>
      {% endfor %}
    {% else %}
      <div class="text-xl sm:text-2xl text-justify">No projects available.</div>
    {% endif %}
  </ul>
</div>
{% endblock %}